-- MySQL Script generated by ChatGPT
-- Base de Datos: tienda_moviltech

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sistema_pedidos_locales
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tienda_moviltech` DEFAULT CHARACTER SET utf8 ;
USE `tienda_moviltech` ;

-- -----------------------------------------------------
-- Table `Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Producto` (
  `idProducto` INT NOT NULL,
  `tipo` VARCHAR(45) NULL,
  `Marca` VARCHAR(45) NULL,
  `Precio` DECIMAL(10,2) NULL,
  `Descripcion` VARCHAR(450) NULL,
  `stock` INT NULL,
  PRIMARY KEY (`idProducto`)
) ENGINE=InnoDB;

-- -----------------------------------------------------
-- Table `Local`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Local` (
  `idLocal` INT NOT NULL,
  `Horario` DATETIME NULL,
  `Ciudad` VARCHAR(45) NULL,
  `Direccion` VARCHAR(100) NULL,
  PRIMARY KEY (`idLocal`)
) ENGINE=InnoDB;

-- -----------------------------------------------------
-- Table `Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cliente` (
  `DNI_Cliente` VARCHAR(45) NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Apellidos` VARCHAR(45) NULL,
  `Telefono` VARCHAR(15) NULL,
  `Fecha_nacimiento` DATE NULL,
  PRIMARY KEY (`DNI_Cliente`)
) ENGINE=InnoDB;

-- -----------------------------------------------------
-- Table `Empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Empleado` (
  `idEmpleado` VARCHAR(45) NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Apellidos` VARCHAR(45) NULL,
  `Telefono` VARCHAR(15) NULL,
  `Jefe_Empleado` VARCHAR(45) NULL,
  `Local_idLocal` INT NOT NULL,
  PRIMARY KEY (`idEmpleado`),
  INDEX `fk_Empleado_Jefe_idx` (`Jefe_Empleado` ASC),
  INDEX `fk_Empleado_Local_idx` (`Local_idLocal` ASC),
  CONSTRAINT `fk_Empleado_Jefe`
    FOREIGN KEY (`Jefe_Empleado`)
    REFERENCES `Empleado` (`idEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Empleado_Local`
    FOREIGN KEY (`Local_idLocal`)
    REFERENCES `Local` (`idLocal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE=InnoDB;

-- -----------------------------------------------------
-- Table `Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pedido` (
  `idPedido` INT NOT NULL,
  `Num_Pedido` VARCHAR(45) NULL,
  `Fecha_Pedido` DATE NULL,
  `Cliente_DNI_Cliente` VARCHAR(45) NOT NULL,
  `Empleado_idEmpleado` VARCHAR(45) NOT NULL,
  `Local_idLocal` INT NOT NULL,
  PRIMARY KEY (`idPedido`),
  INDEX `fk_Pedido_Cliente_idx` (`Cliente_DNI_Cliente` ASC),
  INDEX `fk_Pedido_Empleado_idx` (`Empleado_idEmpleado` ASC),
  INDEX `fk_Pedido_Local_idx` (`Local_idLocal` ASC),
  CONSTRAINT `fk_Pedido_Cliente`
    FOREIGN KEY (`Cliente_DNI_Cliente`)
    REFERENCES `Cliente` (`DNI_Cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedido_Empleado`
    FOREIGN KEY (`Empleado_idEmpleado`)
    REFERENCES `Empleado` (`idEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedido_Local`
    FOREIGN KEY (`Local_idLocal`)
    REFERENCES `Local` (`idLocal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE=InnoDB;

-- -----------------------------------------------------
-- Table `Productos_del_pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Productos_del_pedido` (
  `Pedido_idPedido` INT NOT NULL,
  `Producto_idProducto` INT NOT NULL,
  `Cantidad` INT NULL,
  PRIMARY KEY (`Pedido_idPedido`, `Producto_idProducto`),
  INDEX `fk_Productos_del_pedido_Pedido_idx` (`Pedido_idPedido` ASC),
  INDEX `fk_Productos_del_pedido_Producto_idx` (`Producto_idProducto` ASC),
  CONSTRAINT `fk_Productos_del_pedido_Pedido`
    FOREIGN KEY (`Pedido_idPedido`)
    REFERENCES `Pedido` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Productos_del_pedido_Producto`
    FOREIGN KEY (`Producto_idProducto`)
    REFERENCES `Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE=InnoDB;

-- -----------------------------------------------------
-- Table `Pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pago` (
  `idPago` INT NOT NULL,
  `Fecha_Pago` DATETIME NULL,
  `Metodo_pago` ENUM('Tarjeta', 'Efectivo', 'Transferencia') NULL,
  `Importe` DECIMAL(10,2) NULL,
  `Pedido_idPedido` INT NOT NULL,
  PRIMARY KEY (`idPago`),
  INDEX `fk_Pago_Pedido_idx` (`Pedido_idPedido` ASC),
  CONSTRAINT `fk_Pago_Pedido`
    FOREIGN KEY (`Pedido_idPedido`)
    REFERENCES `Pedido` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE=InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

