-- MySQL Script generated by MySQL Workbench
-- Base de Datos: proyecto_tienda_moviles


SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';


-- -----------------------------------------------------
-- Schema proyecto_tienda_moviles
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `proyecto_tienda_moviles` DEFAULT CHARACTER SET utf8 ;
USE `proyecto_tienda_moviles` ;


-- -----------------------------------------------------
-- Table `Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Producto` (
 `idProducto` INT NOT NULL,
 `tipo` VARCHAR(45) NULL,
 `Marca` VARCHAR(45) NULL,
 `Precio` DECIMAL NULL,
 `Descripcion` VARCHAR(450) NULL,
 PRIMARY KEY (`idProducto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cliente` (
 `DNI_Cliente` VARCHAR(45) NOT NULL,
 `Nombre` VARCHAR(45) NULL,
 `Apellidos` VARCHAR(45) NULL,
 `Telefono` FLOAT NULL,
 PRIMARY KEY (`DNI_Cliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Local`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Local` (
 `idLocal` INT NOT NULL,
 `Horario` DATETIME NULL,
 `Ciudad` VARCHAR(45) NULL,
 PRIMARY KEY (`idLocal`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Empleado` (
 `idEmpleado` VARCHAR(45) NOT NULL,
 `Nombre` VARCHAR(45) NULL,
 `Apellidos` VARCHAR(45) NULL,
 `Telefono` FLOAT NULL,
 `Jefe_Empleado` VARCHAR(45) NULL,
 `Local_idLocal` INT NOT NULL,
 PRIMARY KEY (`idEmpleado`),
 INDEX `fk_Empleado_Empleado1_idx` (`Jefe_Empleado` ASC) VISIBLE,
 INDEX `fk_Empleado_Local1_idx` (`Local_idLocal` ASC) VISIBLE,
 CONSTRAINT `fk_Empleado_Empleado1`
   FOREIGN KEY (`Jefe_Empleado`)
   REFERENCES `Empleado` (`idEmpleado`)
   ON DELETE NO ACTION
   ON UPDATE NO ACTION,
 CONSTRAINT `fk_Empleado_Local1`
   FOREIGN KEY (`Local_idLocal`)
   REFERENCES `Local` (`idLocal`)
   ON DELETE NO ACTION
   ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pedido` (
 `idPedido` INT NOT NULL,
 `Num_Pedido` DOUBLE NULL,
 `Fecha_Pedido` DATETIME NULL,
 `Cliente_DNI_Cliente` VARCHAR(45) NOT NULL,
 `Empleado_idEmpleado` VARCHAR(45) NOT NULL,
 PRIMARY KEY (`idPedido`),
 INDEX `fk_Pedido_Cliente1_idx` (`Cliente_DNI_Cliente` ASC) VISIBLE,
 INDEX `fk_Pedido_Empleado1_idx` (`Empleado_idEmpleado` ASC) VISIBLE,
 CONSTRAINT `fk_Pedido_Cliente1`
   FOREIGN KEY (`Cliente_DNI_Cliente`)
   REFERENCES `Cliente` (`DNI_Cliente`)
   ON DELETE NO ACTION
   ON UPDATE NO ACTION,
 CONSTRAINT `fk_Pedido_Empleado1`
   FOREIGN KEY (`Empleado_idEmpleado`)
   REFERENCES `Empleado` (`idEmpleado`)
   ON DELETE NO ACTION
   ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Productos_del_pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Productos_del_pedido` (
 `Pedido_idPedido` INT NOT NULL,
 `Producto_idProducto` INT NOT NULL,
 `Cantidad` INT NULL,
 INDEX `fk_Productos_del_pedido_Pedido1_idx` (`Pedido_idPedido` ASC) VISIBLE,
 PRIMARY KEY (`Pedido_idPedido`, `Producto_idProducto`),
 INDEX `fk_Productos_del_pedido_Producto1_idx` (`Producto_idProducto` ASC) VISIBLE,
 CONSTRAINT `fk_Productos_del_pedido_Pedido1`
   FOREIGN KEY (`Pedido_idPedido`)
   REFERENCES `Pedido` (`idPedido`)
   ON DELETE NO ACTION
   ON UPDATE NO ACTION,
 CONSTRAINT `fk_Productos_del_pedido_Producto1`
   FOREIGN KEY (`Producto_idProducto`)
   REFERENCES `Producto` (`idProducto`)
   ON DELETE NO ACTION
   ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pago` (
 `idPago` INT NOT NULL,
 `Fecha_Pago` DATETIME NULL,
 `Metodo_pago` ENUM('Tarjeta', 'Efectivo', 'Transferencia') NULL,
 `Importe` DECIMAL NULL,
 `Pedido_idPedido` INT NOT NULL,
 PRIMARY KEY (`idPago`),
 INDEX `fk_Pago_Pedido1_idx` (`Pedido_idPedido` ASC) VISIBLE,
 CONSTRAINT `fk_Pago_Pedido1`
   FOREIGN KEY (`Pedido_idPedido`)
   REFERENCES `Pedido` (`idPedido`)
   ON DELETE NO ACTION
   ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
